apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-cluster
  name: cassandra-cluster-spain-ext
spec:
  type: LoadBalancer
  ports:
    - port: 9042
  selector:
    interface: cassandra-cluster-spain
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-cluster
  name: cassandra-cluster-russia-ext
spec:
  type: LoadBalancer
  ports:
    - port: 9042
  selector:
    interface: cassandra-cluster-russia