kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-cluster-disk-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
