apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cassandra-hpa-spain
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: cassandra-cluster-spain
  targetCPUUtilizationPercentage: 70 # target CPU utilization
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cassandra-hpa-russia
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: cassandra-cluster-russia
  targetCPUUtilizationPercentage: 70 # target CPU utilization
