apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra-cluster-spain
  labels:
    app: cassandra-cluster
spec:
  serviceName: cassandra-cluster-spain
  replicas: 3
  selector:
    matchLabels:
      app: cassandra-cluster
      interface: cassandra-cluster-spain
  template:
    metadata:
      labels:
        app: cassandra-cluster
        interface: cassandra-cluster-spain
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dc
                operator: In
                values:
                - DC1
      containers:
        - name: cassandra-cluster
          image: cassandra
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            limits:
              cpu: 800m
            requests:
              cpu: 500m
          lifecycle:
            preStop:
              exec:
                command: 
                  - /bin/sh
                  - -c
                  - nodetool drain
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-cluster-spain-0.cassandra-cluster-spain.default.svc.cluster.local, cassandra-cluster-russia-0.cassandra-cluster-russia.default.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: POD_IP
              valueFrom:
                fieldRef:
                   fieldPath: status.podIP  
          volumeMounts:
          - name: cassandra-cluster-disk-claim
            mountPath: /var/lib/cassandra/data
  volumeClaimTemplates:
  - metadata:
      name: cassandra-cluster-disk-claim
    spec:
      storageClassName: default
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
